/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TricksIndexRouteImport } from './routes/tricks/index'
import { Route as TrendsIndexRouteImport } from './routes/trends/index'
import { Route as GuidelinesIndexRouteImport } from './routes/guidelines/index'
import { Route as GuidelinesIdRouteImport } from './routes/guidelines/$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksIndexRoute = TricksIndexRouteImport.update({
  id: '/tricks/',
  path: '/tricks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/trends/',
  path: '/trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIndexRoute = GuidelinesIndexRouteImport.update({
  id: '/guidelines/',
  path: '/guidelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIdRoute = GuidelinesIdRouteImport.update({
  id: '/guidelines/$id',
  path: '/guidelines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/trends/': typeof TrendsIndexRoute
  '/tricks/': typeof TricksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines': typeof GuidelinesIndexRoute
  '/trends': typeof TrendsIndexRoute
  '/tricks': typeof TricksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/trends/': typeof TrendsIndexRoute
  '/tricks/': typeof TricksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/guidelines/$id'
    | '/guidelines/'
    | '/trends/'
    | '/tricks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/guidelines/$id'
    | '/guidelines'
    | '/trends'
    | '/tricks'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/guidelines/$id'
    | '/guidelines/'
    | '/trends/'
    | '/tricks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  GuidelinesIdRoute: typeof GuidelinesIdRoute
  GuidelinesIndexRoute: typeof GuidelinesIndexRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
  TricksIndexRoute: typeof TricksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks/': {
      id: '/tricks/'
      path: '/tricks'
      fullPath: '/tricks/'
      preLoaderRoute: typeof TricksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/trends'
      fullPath: '/trends/'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/': {
      id: '/guidelines/'
      path: '/guidelines'
      fullPath: '/guidelines/'
      preLoaderRoute: typeof GuidelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/$id': {
      id: '/guidelines/$id'
      path: '/guidelines/$id'
      fullPath: '/guidelines/$id'
      preLoaderRoute: typeof GuidelinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  GuidelinesIdRoute: GuidelinesIdRoute,
  GuidelinesIndexRoute: GuidelinesIndexRoute,
  TrendsIndexRoute: TrendsIndexRoute,
  TricksIndexRoute: TricksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
